databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: Pythonando-8.0
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vitalab.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database_db_9epc_user
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4